'use strict';
requirejs.config({
    paths: {
        'jquery': '/Scripts/jquery-3.1.1.min',
        'angular': '/Scripts/angular.min',
        'angular-animate': '/Scripts/angular-animate.min',
        'angular-aria': '/Scripts/angular-aria.min',
        'angular-route': '/Scripts/angular-route.min',
        'angular-cookies': '/Scripts/angular-cookies.min',
        'angular-touch': '/Scripts/angular-touch.min',
        'angular-message': '/Scripts/angular-messages.min',
        'ng-file-upload': '/Scripts/ng-file-upload-all.min',
        'ui-grid': '/Scripts/ui-grid.min',
        'ui-bootstrap': '/Scripts/angular-ui/ui-bootstrap.min',
        'ui-bootstrap-tpls': '/Scripts/angular-ui/ui-bootstrap-tpls.min',
        'bootstrap': '/Scripts/bootstrap.min',
        'underscore': '/Scripts/underscore.min',
        'defaultExtends': '/Scripts/WebCore/defaultExtends',
        'angularJsExtends': '/Scripts/WebCore/angularJsExtends',
        'angularAMD': '/Scripts/angularAMD.min',
        // requirejs-plugins
        'text': '/Scripts/text',
        'async': '/Scripts/requirejs-plugins/async',
        'font': '/Scripts/requirejs-plugins/font',
        'goog': '/Scripts/requirejs-plugins/goog',
        'image': '/Scripts/requirejs-plugins/image',
        'json': '/Scripts/requirejs-plugins/json',
        'noext': '/Scripts/requirejs-plugins/noext',
        'mdown': '/Scripts/requirejs-plugins/mdown',
        'propertyParser': '/Scripts/requirejs-plugins/propertyParser'
    },
    shim: {
        'angular': {
            deps: ['jquery'],
            exports: 'angular'
        },
        'angular-animate': ['angular'],
        'angular-aria': ['angular'],
        'angular-route': ['angular'],
        'angular-cookies': ['angular'],
        'angular-touch': ['angular'],
        'angular-message': ['angular'],
        'bootstrap': ['jquery'],
        'ng-file-upload': ['angular'],
        'ui-grid': ['angular'],
        'ui-bootstrap': ['angular'],
        'ui-bootstrap-tpls': ['angular', 'ui-bootstrap'],
        'angularJsExtends': ['angular', 'underscore'],
        'angularAMD': ['underscore',
            'defaultExtends',
            'angular',
            'angular-animate',
            'angular-aria',
            'angular-route',
            'angular-cookies',
            'angular-touch',
            'angular-message',
            'bootstrap',
            'ui-bootstrap',
            'ui-bootstrap-tpls',
            'ng-file-upload',
            'ui-grid',
            'angularJsExtends']
    },
    deps: ['app']
});