(function(h,r){"object"===typeof module&&module.exports?module.exports=r(require("./URI")):"function"===typeof define&&define.amd?define(["./URI"],r):h.URITemplate=r(h.URI,h)})(this,function(h,r){function b(a){if(b._cache[a])return b._cache[a];if(!(this instanceof b))return new b(a);this.expression=a;b._cache[a]=this;return this}function t(a){this.data=a;this.cache={}}var x=r&&r.URITemplate,y=Object.prototype.hasOwnProperty,v=b.prototype,w={"":{prefix:"",separator:",",named:!1,empty_name_separator:!1,
encode:"encode"},"+":{prefix:"",separator:",",named:!1,empty_name_separator:!1,encode:"encodeReserved"},"#":{prefix:"#",separator:",",named:!1,empty_name_separator:!1,encode:"encodeReserved"},".":{prefix:".",separator:".",named:!1,empty_name_separator:!1,encode:"encode"},"/":{prefix:"/",separator:"/",named:!1,empty_name_separator:!1,encode:"encode"},";":{prefix:";",separator:";",named:!0,empty_name_separator:!1,encode:"encode"},"?":{prefix:"?",separator:"&",named:!0,empty_name_separator:!0,encode:"encode"},
"&":{prefix:"&",separator:"&",named:!0,empty_name_separator:!0,encode:"encode"}};b._cache={};b.EXPRESSION_PATTERN=/\{([^a-zA-Z0-9%_]?)([^\}]+)(\}|$)/g;b.VARIABLE_PATTERN=/^([^*:.](?:\.?[^*:.])*)((\*)|:(\d+))?$/;b.VARIABLE_NAME_PATTERN=/[^a-zA-Z0-9%_.]/;b.LITERAL_PATTERN=/[<>{}"`^| \\]/;b.expand=function(a,c,d){var l=w[a.operator],h=l.named?"Named":"Unnamed";a=a.variables;var g=[],e,q;for(q=0;e=a[q];q++){var f=c.get(e.name);if(0===f.type&&d&&d.strict)throw Error('Missing expansion value for variable "'+
e.name+'"');if(f.val.length){if(1<f.type&&e.maxlength)throw Error('Invalid expression: Prefix modifier not applicable to variable "'+e.name+'"');g.push(b["expand"+h](f,l,e.explode,e.explode&&l.separator||",",e.maxlength,e.name))}else f.type&&g.push("")}return g.length?l.prefix+g.join(l.separator):""};b.expandNamed=function(a,c,b,l,u,g){var e="",d=c.encode;c=c.empty_name_separator;var f=!a[d].length,k=2===a.type?"":h[d](g),n;var p=0;for(n=a.val.length;p<n;p++){if(u){var m=h[d](a.val[p][1].substring(0,
u));2===a.type&&(k=h[d](a.val[p][0].substring(0,u)))}else f?(m=h[d](a.val[p][1]),2===a.type?(k=h[d](a.val[p][0]),a[d].push([k,m])):a[d].push([void 0,m])):(m=a[d][p][1],2===a.type&&(k=a[d][p][0]));e&&(e+=l);b?e+=k+(c||m?"=":"")+m:(p||(e+=h[d](g)+(c||m?"=":"")),2===a.type&&(e+=k+","),e+=m)}return e};b.expandUnnamed=function(a,c,d,l,b){var g="",e=c.encode;c=c.empty_name_separator;var q=!a[e].length,f;var k=0;for(f=a.val.length;k<f;k++){if(b)var n=h[e](a.val[k][1].substring(0,b));else q?(n=h[e](a.val[k][1]),
a[e].push([2===a.type?h[e](a.val[k][0]):void 0,n])):n=a[e][k][1];g&&(g+=l);if(2===a.type){var p=b?h[e](a.val[k][0].substring(0,b)):a[e][k][0];g+=p;g=d?g+(c||n?"=":""):g+","}g+=n}return g};b.noConflict=function(){r.URITemplate===b&&(r.URITemplate=x);return b};v.expand=function(a,c){var d="";this.parts&&this.parts.length||this.parse();a instanceof t||(a=new t(a));for(var l=0,h=this.parts.length;l<h;l++)d+="string"===typeof this.parts[l]?this.parts[l]:b.expand(this.parts[l],a,c);return d};v.parse=function(){var a=
this.expression,c=b.EXPRESSION_PATTERN,d=b.VARIABLE_PATTERN,l=b.VARIABLE_NAME_PATTERN,h=b.LITERAL_PATTERN,g=[],e=0,q=function(a){if(a.match(h))throw Error('Invalid Literal "'+a+'"');return a};for(c.lastIndex=0;;){var f=c.exec(a);if(null===f){g.push(q(a.substring(e)));break}else g.push(q(a.substring(e,f.index))),e=f.index+f[0].length;if(!w[f[1]])throw Error('Unknown Operator "'+f[1]+'" in "'+f[0]+'"');if(!f[3])throw Error('Unclosed Expression "'+f[0]+'"');var k=f[2].split(",");for(var n=0,p=k.length;n<
p;n++){var m=k[n].match(d);if(null===m)throw Error('Invalid Variable "'+k[n]+'" in "'+f[0]+'"');if(m[1].match(l))throw Error('Invalid Variable Name "'+m[1]+'" in "'+f[0]+'"');k[n]={name:m[1],explode:!!m[3],maxlength:m[4]&&parseInt(m[4],10)}}if(!k.length)throw Error('Expression Missing Variable(s) "'+f[0]+'"');g.push({expression:f[0],operator:f[1],variables:k})}g.length||g.push(q(a));this.parts=g;return this};t.prototype.get=function(a){var c=this.data,d={type:0,val:[],encode:[],encodeReserved:[]};
if(void 0!==this.cache[a])return this.cache[a];this.cache[a]=d;c="[object Function]"===String(Object.prototype.toString.call(c))?c(a):"[object Function]"===String(Object.prototype.toString.call(c[a]))?c[a](a):c[a];if(void 0!==c&&null!==c)if("[object Array]"===String(Object.prototype.toString.call(c))){var b=0;for(a=c.length;b<a;b++)void 0!==c[b]&&null!==c[b]&&d.val.push([void 0,String(c[b])]);d.val.length&&(d.type=3)}else if("[object Object]"===String(Object.prototype.toString.call(c))){for(b in c)y.call(c,
b)&&void 0!==c[b]&&null!==c[b]&&d.val.push([b,String(c[b])]);d.val.length&&(d.type=2)}else d.type=1,d.val.push([void 0,String(c)]);return d};h.expand=function(a,c){var d=(new b(a)).expand(c);return new h(d)};return b});